### PR TITLE
Homework 1

### PR DESCRIPTION
**Pull request by piechart**
# I have made things!

## Checklist

- [x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [x] I have created at least one test case for the changes I have made
- [x] I have updated my GitHub account to contain my real name, so I can be credited for my work
- [x] I have named the source branch properly: `homework-${HOMEWORK_NUMBER}`
- [x] I have made the changes to the correct folder: `students/${GITHUB_ACCOUNT}/${HOMEWORK_NUMBER}`
- [x] I understand the rules of the project: including code quality, deadline, and the process
- [x] I learned something new!

### CODE REVIEW

**Comment by piechart** [comment]
@sobolevn 
1. Wtf with Danger JS Action - `issues/24/comments` - `Resource not accessible by integration`?
2. Should inputs be hardcoded with default values as they pause Travis execution & lead to `No output has been received in the last 10m0s`?
3. Maybe magic comment to trigger full CI cycle execution in addition to PR creation?

**Comment by sobolevn** [comment]
1. You can ignore `danger` for now, I will fix that. There's a bug in `danger-js` or `Github Actions`: https://github.com/danger/danger-js/issues/918
2. No, files should respect the correct input flow. It should only happen under `if __name__ == '__main__':` and it should not break the execution

**Comment by lerastromtsova** [comment]
@sobolevn , I have the same problem with inputs. Even though the input in my file 'runtests.py' is under `if  __name__ == '__main__':`, the program execution gets stuck on CI server and fails after 11 minutes.

**Comment by sobolevn** [comment]
@lerastromtsova @piechart this happens because we directly execute `runtests.py` here: https://github.com/sobolevn/itmo-2019/blob/master/bin/homework1.sh#L18

So, `if __name__` is also executed. You can possibly fix that by creating a new file called `simple_test_framework.py` and moving the core logic there. While `runtests.py` is just a RUNNER for your tests. 

In this setup you can store, run, and tests your code easily.

**Pull request closed without merging**
